[package]
name = "s9_binance_adapter"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Silvennoinen <alex@silvennoinen.de>"]

[dependencies]
s9_binance_websocket = { git = "https://github.com/AlexSilver9/s9_binance_websocket.git" }